= Yirmiyahu 9av 2024 notes
:toc:

== Highlighted passages maybe read

=== Ch 3

ch 3:11 ff

Jeremiah 3:12 (NKJV): Return, backsliding Israel,’ says the Lord;‘I will not cause My anger to fall on you.For I am merciful,’

=== ch 4

Jeremiah 4:1–2 (NKJV): If you will return, O Israel," says the Lord,"Return to Me;And if you will put away your abominations out of My sight,Then you shall not be moved.2And you shall swear, ‘The Lord lives,’

followed by warning...

== ch 5

!! captivy in a strange land was GOD's punishment for them serving goreign gods... you like that foreign culture so much to serve their gods, here, be forced into their land!

Jeremiah 5:19 (LHB): וְהָיָה֙ כִּ֣י תֹאמְר֔וּ תַּ֣חַת מֶ֗ה עָשָׂ֨ה יְהֹוָ֧ה אֱלֹהֵ֛ינוּ לָ֖נוּ אֶת־כָּל־אֵ֑לֶּה וְאָמַרְתָּ֣ אֲלֵיהֶ֗ם כַּאֲשֶׁ֨ר עֲזַבְתֶּ֤ם אוֹתִי֙ וַתַּעַבְד֞וּ אֱלֹהֵ֤י נֵכָר֙ בְּאַרְצְכֶ֔ם כֵּ֚ן תַּעַבְד֣וּ זָרִ֔ים בְּאֶ֖רֶץ לֹ֥א לָכֶֽם׃ ס


=== ch 6

SIEGE , shepherds

Jeremiah 6:10–11 (NKJV): Behold, the word of the Lord is a reproach to them;They have no delight in it.11Therefore I am full of the fury of the Lord.I am weary of holding it in."I will pour it out on the children outside,

Jeremiah 6:13 (NKJV): Because from the least of them even to the greatest of them,Everyone is given to covetousness;And from the prophet even to the priest,Everyone deals falsely.



