= Yeshayahu 1:1-x Notes
:toc:

==== 1:4

נִֽאֲצ֛וּ אֶת־קְד֥וֹשׁ יִשְׂרָאֵ֖ל נָזֹ֥רוּ אָחֽוֹר

Instead of נָסֹגוּ אחור we have נָזֹ֥רוּ אָחֽוֹר!

> Marti, for instance, proposes emending to נָסֹגוּ אחור, ‘they have turned backward’, i.e. backslidden, which occurs several times elsewhere, and which would be attractive because of the contrast at 50:5 - Will ICC

> נזרו is the perfect niph‘al of זור I, attested otherwise only at Ezek. 14:5 in a not dissimilar context, meaning ‘they have become estranged’. אחור, a noun meaning ‘the back part’, is used adverbially, as frequently, here with the pregnant sense of ‘to go backwards’, a common enough construction;... The phrase therefore means that they have abandoned following Yahweh in favour of some older form of apostasy. Although many have found this difficult and proposed alternatives, none seems preferable...

עָזְב֣וּ / נִֽאֲצ֛וּ

יֹ֭שְׁבֵי חֹ֣שֶׁךְ וְצַלְמָ֑וֶת אֲסִירֵ֖י עֳנִ֣י וּבַרְזֶֽל׃ כִּֽי־הִמְר֥וּ אִמְרֵי־אֵ֑ל וַעֲצַ֖ת עֶלְי֣וֹן נָאָֽצוּ׃
- Psalm 107:10-11

See this and past v. 11 for hope







